name: DailyRewards
version: 1.0
main: Reward.Rewards
api-version: "1.21"
authors: [ar1hurgit]
commands:
  rewards:
    description: Open daily rewards menu
    usage: /rewards [admin]
permissions:
  dailyrewards.admin:
    description: Access to admin commands
    default: op