name: DailyRewards
version: 1.0.5
main: Reward.Rewards
api-version: "1.21"
authors: [ar1hurgit]
commands:
  rewards:
    description: Open daily rewards menu
    usage: /rewards [admin]
permissions:
  dailyrewards.admin.*:
    description: Access to all admin commands
    default: op
    children:
      dailyrewards.admin.set: true
      dailyrewards.admin.day: true